### ISSUE TITLE
提示无法在虚拟机上运行

### ISSUE THREAD

**Issue by w3571825** [Fackblack/douyinlive#71]
win10专业版，群晖7.2，运行提示sorry.this application cannot run undrer a virtual machine.
尝试更换位置无用

**Comment by Fackblack** [comment]
> win10专业版，群晖7.2，运行提示sorry.this application cannot run undrer a virtual machine.
> 尝试更换位置无用

暂无适配

**Comment by w3571825** [comment]
知道了。 感谢作者无私奉献
