### ISSUE TITLE
[功能请求] 弹幕录制功能

### ISSUE THREAD

**Issue by xxshz1611** [Fackblack/douyinlive#73]
举例，[b站录播姬](https://github.com/BililiveRecorder/BililiveRecorder)可以在录制b站直播的同时，爬取实时弹幕生成.xml文件。如果作者也有相近意愿，希望考虑增加与之类似的实时弹幕录制功能。

具体的效果如下，将.xml文件转换为.ass文件后，用potplayer视频播放器导入字幕后几近还原了完整的直播体验。

![捕获](https://github.com/user-attachments/assets/57273546-ee05-4d18-97a7-c67dc2752487)

**Comment by Fackblack** [comment]
> 举例，[b站录播姬](https://github.com/BililiveRecorder/BililiveRecorder)可以在录制b站直播的同时，爬取实时弹幕生成.xml文件。如果作者也有相近意愿，希望考虑增加与之类似的实时弹幕录制功能。
> 
> 具体的效果如下，将.xml文件转换为.ass文件后，用potplayer视频播放器导入字幕后几近还原了完整的直播体验。
> 
> ![捕获](https://github.com/user-attachments/assets/57273546-ee05-4d18-97a7-c67dc2752487)
> 
> 
> 
> 

勿发不相关的
