### ISSUE TITLE
希望作者增加一个功能，关于专属会员的直播

### ISSUE THREAD

**Issue by bushiyaorenhuade** [Fackblack/douyinlive#89]
现在抖音有那个专属会员，专属会员的直播，不是会员是看不到的。我现在是莫一个主播的会员，但是现在没方式下载，希望作者能做下这个功能。

**Comment by icemaple0404** [comment]
这个应该很难实现吧 这样如果可以录制 就要这个软件跟每个人的抖音账号关联才行 否则怎么进到会员直播间呢
