### ISSUE TITLE
感觉打开这个软件，谷歌浏览器无法翻墙了，很多时候会提示网页无法访问

### ISSUE THREAD

**Issue by shutwin** [Fackblack/douyinlive#99]
不知道是不是软件的问题，更新到1.7版本，网页访问会出现问题，不知道是不是软件的问题，哈
谢谢作者的无私奉献！！！

**Comment by shutwin** [comment]
打不开YouTube和谷歌搜索等国外的常见网站。
![屏幕截图_26-10-2024_233738_www youtube com](https://github.com/user-attachments/assets/798d86de-7546-4fd7-83cf-fbd4848bcecf)

**Comment by olalala10** [comment]
这个软件和代理软件会出现冲突 建议打开tun模式即可正常使用

**Comment by jennifer19921130** [comment]
我也。
